name: CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  downstream-lcw:
    runs-on: ubuntu-latest
    name: Downstream LCW

    steps:
      - name: Checkout LCI
        uses: actions/checkout@v4
        with:
          path: lci

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build libfabric-bin libfabric-dev

      - name: Checkout LCW
        uses: actions/checkout@v4
        with:
          repository: JiakunYan/lcw
          path: lcw

      - name: Configure
        shell: bash
        run: |
            cmake \
                -Slcw \
                -Bbuild \
                -GNinja \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DLCI_DEBUG=ON \
                -DLCI_NETWORK_BACKENDS=ofi,ibv \
                -DLCI_USE_TCMALLOC=OFF \
                -DCMAKE_VERBOSE_MAKEFILE=ON \
                -DLCW_DEBUG=ON \
                -DLCW_USE_CTEST_LAUNCHER=${{ github.workspace }}/lci/lcrun \
                -DFETCHCONTENT_SOURCE_DIR_LCI=${{ github.workspace }}/lci

      - name: Build
        shell: bash
        # Build your program with the given configuration
        run: |
            cmake --build build --target all

      - name: Test
        shell: bash
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: |
            cd build
            export LCW_BACKEND_AUTO=lci2
            ctest --extra-verbose --timeout 300 --rerun-failed --output-on-failure